use_frameworks!

platform :ios, '10.0'

target 'MFMediaView_Example' do
  pod 'MFMediaView', :path => '../'

  # pod 'SVGAPlayer'
  # pod 'libpag'

  # pod 'Reveal-SDK', '24', :configurations => ['Debug']

  target 'MFMediaView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'MFFileDownloader', :git => 'https://github.com/MoreFunTech/MFFileDownloader.git'
    
  end
end
