use_frameworks!

platform :ios, '10.0'

target 'MFMediaView_Example' do
  pod 'MFMediaView', :path => '../'

  target 'MFMediaView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
